In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings 
warnings.filterwarnings("ignore")

In [278]:
df = pd.read_excel("flight_price.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [279]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [280]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [281]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [282]:
df.shape   # (rows,columns)

(10683, 11)

In [283]:
df.isnull().sum()   # route and total_stop has null value

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [284]:
df.dropna(axis=0,inplace=True)

In [285]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [286]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"])

In [287]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [288]:
"nikhil/daroch".split("/")[1]

'daroch'

In [289]:
# df["day"] = df["Date_of_Journey"].str.split("/").str[0]
# # df["month"] = df["Date_of_Journey"].str.split("/").str[1]
# # df["year"] = df["Date_of_Journey"].str.split("/").str[2]

# this is also an approch to change the date

In [290]:
# df.sample()
df["days"] = df.Date_of_Journey.dt.day
df["month"] = df.Date_of_Journey.dt.month
df["year"] = df.Date_of_Journey.dt.year

In [291]:
df.drop("Date_of_Journey",axis=1,inplace=True)

In [292]:
df["Arrival_Time"] = df["Arrival_Time"].apply(lambda x:x.split(" ")[0])

In [293]:
df["Arrival_hour"] = df["Arrival_Time"].str.split(":").str[0]    # .str.split works on strings and convert it into series
# .split works on single string 
df["Arrival_min"] = df["Arrival_Time"].str.split(":").str[1]

In [294]:
df.drop("Arrival_Time",axis=1,inplace=True)

In [295]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Duration         10682 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10682 non-null  object
 8   Price            10682 non-null  int64
 9   days             10682 non-null  int32
 10  month            10682 non-null  int32
 11  year             10682 non-null  int32
 12  Arrival_hour     10682 non-null  object
 13  Arrival_min      10682 non-null  object
dtypes: int32(3), int64(1), object(10)
memory usage: 1.1+ MB

In [296]:
df["Arrival_hour"] = df["Arrival_hour"].astype(int)
df["Arrival_min"] = df["Arrival_min"].astype(int)

In [297]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Duration         10682 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10682 non-null  object
 8   Price            10682 non-null  int64
 9   days             10682 non-null  int32
 10  month            10682 non-null  int32
 11  year             10682 non-null  int32
 12  Arrival_hour     10682 non-null  int64
 13  Arrival_min      10682 non-null  int64
dtypes: int32(3), int64(3), object(8)
memory usage: 1.1+ MB

In [298]:
df["Dep_hour"] = df.Dep_Time.str.split(":").str[0]
df["Dep_mins"] = df.Dep_Time.str.split(":").str[1]

In [299]:
df.drop("Dep_Time",axis=1,inplace=True)

In [300]:
df["Dep_hour"] = df["Dep_hour"].astype(int)
df["Dep_mins"] = df["Dep_mins"].astype(int)

In [301]:
df.Total_Stops.unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [302]:
df["Total_Stops"] = df["Total_Stops"].map({"non-stop":0,"1 stop":1,"2 stops":2,"3 stops":3,"4 stops":4})

In [303]:
df.Total_Stops.unique()

array([0, 2, 1, 3, 4])

In [304]:
df["duration_hour"] = df.Duration.str.split().str[0].str.split("h").str[0]

In [305]:
df.drop("Duration",axis=1,inplace=True)

In [306]:
df

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,days,month,year,Arrival_hour,Arrival_min,Dep_hour,Dep_mins,duration_hour
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,1,3,2019,21,35,16,50,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,No info,4107,9,4,2019,22,25,19,55,2
10679,Air India,Kolkata,Banglore,CCU → BLR,0,No info,4145,27,4,2019,23,20,20,45,2
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,No info,7229,27,4,2019,11,20,8,20,3
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,No info,12648,1,3,2019,14,10,11,30,2
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2,No info,11753,9,5,2019,19,15,10,55,8