In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({"description":["hello my name is nikhil right now i am at coder roots and studing data science"]}) 
df

                                         description
0  hello my name is nikhil right now i am at code...

In [4]:
pd.set_option("display.max_colwidth",1000)  # to seee the whole text
df

                                                                      description
0  hello my name is nikhil right now i am at coder roots and studing data science

In [12]:
a= " hello my name is nikhil"
len(a)

24

In [15]:
len(a.split())

5

In [19]:
df["word_count"]=df["description"].apply(lambda x:len(x.split()))
df

,description,word_count
0,hello my name is nikhil right now i am at coder roots and studing data science,16

In [12]:
# rolling function

df1 = pd.DataFrame({"a":[1,2,3,4,5,6,7,8,9]})
df1

   a
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [6]:
df1.rolling(window=1).mean()  # mean with with itself only one element is included

     a
0  1.0
1  2.0
2  3.0
3  4.0
4  5.0
5  6.0
6  7.0
7  8.0
8  9.0

In [7]:
df1.rolling(window=2).mean()

     a
0  NaN
1  1.5
2  2.5
3  3.5
4  4.5
5  5.5
6  6.5
7  7.5
8  8.5

In [3]:
import numpy as np

In [4]:
np.random.choice(["A","B"])

np.str_('B')

In [8]:
df1["group"] = np.random.choice(["A","B"],size=9)
df1

   a group
0  1     A
1  2     A
2  3     B
3  4     A
4  5     B
5  6     B
6  7     B
7  8     B
8  9     B

In [10]:
df1.groupby("group")["a"].sum()

group
A     7
B    38
Name: a, dtype: int64

In [16]:
df1.groupby("group")["a"].rolling(window=2).sum()

group
A      1     NaN
       2     5.0
       4     8.0
       6    12.0
B      0     NaN
       3     5.0
       5    10.0
       7    14.0
       8    17.0
Name: a, dtype: float64

In [18]:
data = pd.DataFrame({"a":["2024-03-08","2024-02-06","2024-04-09"]})
data

            a
0  2024-03-08
1  2024-02-06
2  2024-04-09

In [68]:
data.dtypes

a    object
dtype: object

In [19]:
data["updated_col"]=pd.to_datetime(data["a"])
data

            a updated_col
0  2024-03-08  2024-03-08
1  2024-02-06  2024-02-06
2  2024-04-09  2024-04-09

In [72]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   a            3 non-null      object
 1   updated_col  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [74]:
data.dtypes

a                      object
updated_col    datetime64[ns]
dtype: object

In [20]:
data["updated_col"].dt.day

0    8
1    6
2    9
Name: updated_col, dtype: int32

In [14]:
pd.Timestamp.now()

Timestamp('2026-03-29 16:43:05.775615')

In [19]:
# to check the execution time of code 
start = pd.Timestamp.now()
for i in range(1000):
    pass
end = pd.Timestamp.now()
print("exection time of code is : ", end-start)

exection time of code is :  0 days 00:00:00.000657

In [20]:
from datetime import datetime

date = "2026-03-11"
date

'2026-03-11'

In [21]:
datetime.strptime(date,"%y-%m-%d")

ValueError: time data '2026-03-11' does not match format '%y-%m-%d'

In [ ]:
d = pd.Timedelta(days=1,hours=5,minutes=40)
d  # timedelta is a differnce of time

Timedelta('1 days 05:40:00')

In [42]:
date = pd.to_datetime("2026-03-11")
date

Timestamp('2026-03-11 00:00:00')

In [ ]:
d+date # gives the next date

Timestamp('2026-03-12 05:40:00')