In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("taxonomy.csv")
data

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [8]:
data.tail()

             0                             1       2                     3
286  111-01-07              Workplace Rights  111-01  Advocacy & Legal Aid
287     111-02                     Mediation     111                 Legal
288     111-03                        Notary     111                 Legal
289     111-04                Representation     111                 Legal
290     111-05  Translation & Interpretation     111                 Legal

In [10]:
data.head()

             0                  1          2               3
0  taxonomy_id               name  parent_id     parent_name
1          101          Emergency        NaN             NaN
2       101-01  Disaster Response        101       Emergency
3       101-02     Emergency Cash        101       Emergency
4    101-02-01  Help Pay for Food     101-02  Emergency Cash

In [13]:
data.shape

(291, 4)

In [17]:
data.dtypes

0    object
1    object
2    object
3    object
dtype: object

In [19]:
data.info

<bound method DataFrame.info of                0                             1          2  \
0    taxonomy_id                          name  parent_id
1            101                     Emergency        NaN
2         101-01             Disaster Response        101
3         101-02                Emergency Cash        101
4      101-02-01             Help Pay for Food     101-02
..           ...                           ...        ...
286    111-01-07              Workplace Rights     111-01
287       111-02                     Mediation        111
288       111-03                        Notary        111
289       111-04                Representation        111
290       111-05  Translation & Interpretation        111

                        3
0             parent_name
1                     NaN
2               Emergency
3               Emergency
4          Emergency Cash
..                    ...
286  Advocacy & Legal Aid
287                 Legal
288                 Legal
289                 Legal
290                 Legal

[291 rows x 4 columns]>

In [22]:
data[0:20:2]

              0                               1          2                 3
0   taxonomy_id                            name  parent_id       parent_name
2        101-01               Disaster Response        101         Emergency
4     101-02-01               Help Pay for Food     101-02    Emergency Cash
6     101-02-03            Help Pay for Housing     101-02    Emergency Cash
8     101-02-05             Help Pay for School     101-02    Emergency Cash
10       101-03                  Emergency Food        101         Emergency
12       101-05       Help Find Missing Persons        101         Emergency
14    101-06-01            Help Escape Violence     101-06  Immediate Safety
16       101-07  Psychiatric Emergency Services        101         Emergency
18       102-01               Community Gardens        102              Food

In [23]:
# revise accesing the data in dataframes

In [24]:
# implicit indexing

In [ ]:
# data.iloc[0:3]  # iloc always require internal indexes

             0                  1          2            3
0  taxonomy_id               name  parent_id  parent_name
1          101          Emergency        NaN          NaN
2       101-01  Disaster Response        101    Emergency

In [ ]:
# explicit or named indexing

data.loc[0:3]

             0                  1          2            3
0  taxonomy_id               name  parent_id  parent_name
1          101          Emergency        NaN          NaN
2       101-01  Disaster Response        101    Emergency
3       101-02     Emergency Cash        101    Emergency

In [55]:
data.loc[0:5,["taxonomy_id","name"]]

  taxonomy_id                     name
0         101                Emergency
1      101-01        Disaster Response
2      101-02           Emergency Cash
3   101-02-01        Help Pay for Food
4   101-02-02  Help Pay for Healthcare
5   101-02-03     Help Pay for Housing

In [3]:
data["taxonomy_id"][2:5]

2       101-02
3    101-02-01
4    101-02-02
Name: taxonomy_id, dtype: object

In [3]:
s = pd.Series(list(data["taxonomy_id"][2:5]))
s

0       101-02
1    101-02-01
2    101-02-02
dtype: object

In [ ]:
data.drop("taxonomy_id",axis=True) #inplace means to change in original

                             name parent_id           parent_name
0                       Emergency       NaN                   NaN
1               Disaster Response       101             Emergency
2                  Emergency Cash       101             Emergency
3               Help Pay for Food    101-02        Emergency Cash
4         Help Pay for Healthcare    101-02        Emergency Cash
..                            ...       ...                   ...
285              Workplace Rights    111-01  Advocacy & Legal Aid
286                     Mediation       111                 Legal
287                        Notary       111                 Legal
288                Representation       111                 Legal
289  Translation & Interpretation       111                 Legal

[290 rows x 3 columns]

In [ ]:
data.astype("object").describe()  # treat all as categorial data  ,, describe -->> statistical info of num columns

       taxonomy_id          name  parent_id       parent_name
count          290           290        279               279
unique         290           183         60                50
top         111-05  Nursing Home  106-06-07  Health Education
freq             1             4         11                15

In [19]:
data.reset_index(drop=True)
data

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [8]:
data.set_index("name",inplace=True)

In [25]:
data

                             taxonomy_id parent_id           parent_name
name
Emergency                            101       NaN                   NaN
Disaster Response                 101-01       101             Emergency
Emergency Cash                    101-02       101             Emergency
Help Pay for Food              101-02-01    101-02        Emergency Cash
Help Pay for Healthcare        101-02-02    101-02        Emergency Cash
...                                  ...       ...                   ...
Workplace Rights               111-01-07    111-01  Advocacy & Legal Aid
Mediation                         111-02       111                 Legal
Notary                            111-03       111                 Legal
Representation                    111-04       111                 Legal
Translation & Interpretation      111-05       111                 Legal

[290 rows x 3 columns]

In [9]:
data.loc["Emergency"]

taxonomy_id    101
parent_id      NaN
parent_name    NaN
Name: Emergency, dtype: object

In [10]:
data.reset_index(drop=True, inplace=True)

In [11]:
data.isnull().sum()

taxonomy_id     0
parent_id      11
parent_name    11
dtype: int64

In [12]:
data.dropna()  # will drop all null values from rows

    taxonomy_id parent_id           parent_name
1        101-01       101             Emergency
2        101-02       101             Emergency
3     101-02-01    101-02        Emergency Cash
4     101-02-02    101-02        Emergency Cash
5     101-02-03    101-02        Emergency Cash
..          ...       ...                   ...
285   111-01-07    111-01  Advocacy & Legal Aid
286      111-02       111                 Legal
287      111-03       111                 Legal
288      111-04       111                 Legal
289      111-05       111                 Legal

[279 rows x 3 columns]

In [50]:
# inputation --> means replacing missing values with some other values 
# numerical value will be replaced with mean and median and outlayers will be replaced with meadian
# categorial data --> will be replaced with mode

In [54]:
data.fillna(0)  # this will used to fill null values

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency         0                     0
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [62]:
d = {"A" : [1,2,None,3,4,5,None],
      "B" : [6,None,7,8,None,None,9]
}

In [65]:
df = pd.DataFrame(d)
df

     A    B
0  1.0  6.0
1  2.0  NaN
2  NaN  7.0
3  3.0  8.0
4  4.0  NaN
5  5.0  NaN
6  NaN  9.0

In [ ]:
df["A"].mean()

np.float64(3.0)

In [70]:
df["A"].fillna(df["A"].mean())  # will fill all the nan values with mean of A

0    1.0
1    2.0
2    3.0
3    3.0
4    4.0
5    5.0
6    3.0
Name: A, dtype: float64

In [72]:
df.duplicated().sum()  # want to see duplicate rows

np.int64(0)

In [81]:
data["name"]

0                         Emergency
1                 Disaster Response
2                    Emergency Cash
3                 Help Pay for Food
4           Help Pay for Healthcare
                   ...
285                Workplace Rights
286                       Mediation
287                          Notary
288                  Representation
289    Translation & Interpretation
Name: name, Length: 290, dtype: object