In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("taxonomy.csv")
df

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [22]:
# concatinate two data frames either horizontally or vertically

In [4]:
data = {"key1":[1,2,3,4,5],
"key2":[6,7,8,9,10],"key3":[11,12,13,14,15]}
d1 = pd.DataFrame(data)
d1

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [6]:
d2 = pd.DataFrame({"key1":[1,2,6,5,8,8],
"key4":[6,7,8,9,0,11],"key5":[1,2,3,4,5,10]})
d2

   key1  key4  key5
0     1     6     1
1     2     7     2
2     6     8     3
3     5     9     4
4     8     0     5
5     8    11    10

In [42]:
pd.merge(d1,d2,how="inner")  # will merge two dataframes based on their common elements

   key1  key2  key3  key4  key5
0     1     6    11     6     1
1     2     7    12     7     2
2     5    10    15     9     4

In [44]:
pd.merge(d1,d2,how="left")  # left data frame will be printed and based on left right elements will be printed which are comman

   key1  key2  key3  key4  key5
0     1     6    11   6.0   1.0
1     2     7    12   7.0   2.0
2     3     8    13   NaN   NaN
3     4     9    14   NaN   NaN
4     5    10    15   9.0   4.0

In [46]:
pd.merge(d1,d2,how="right")  # similar to right merge

   key1  key2  key3  key4  key5
0     1   6.0  11.0     6     1
1     2   7.0  12.0     7     2
2     6   NaN   NaN     8     3
3     5  10.0  15.0     9     4
4     8   NaN   NaN     0     5
5     8   NaN   NaN    11    10

In [ ]:
pd.merge(d1,d2,how="outer")   # all the comman elemnets of the common column from both data frame

   key1  key2  key3  key4  key5
0     1   6.0  11.0   6.0   1.0
1     2   7.0  12.0   7.0   2.0
2     3   8.0  13.0   NaN   NaN
3     4   9.0  14.0   NaN   NaN
4     5  10.0  15.0   9.0   4.0
5     6   NaN   NaN   8.0   3.0
6     8   NaN   NaN   0.0   5.0
7     8   NaN   NaN  11.0  10.0

In [9]:
pd.merge(d1,d2,how="cross") # all permutation will be possible

    key1_x  key2  key3  key1_y  key4  key5
0        1     6    11       1     6     1
1        1     6    11       2     7     2
2        1     6    11       6     8     3
3        1     6    11       5     9     4
4        1     6    11       8     0     5
5        1     6    11       8    11    10
6        2     7    12       1     6     1
7        2     7    12       2     7     2
8        2     7    12       6     8     3
9        2     7    12       5     9     4
10       2     7    12       8     0     5
11       2     7    12       8    11    10
12       3     8    13       1     6     1
13       3     8    13       2     7     2
14       3     8    13       6     8     3
15       3     8    13       5     9     4
16       3     8    13       8     0     5
17       3     8    13       8    11    10
18       4     9    14       1     6     1
19       4     9    14       2     7     2
20       4     9    14       6     8     3
21       4     9    14       5     9     4
22       4     9    14       8     0     5
23       4     9    14       8    11    10
24       5    10    15       1     6     1
25       5    10    15       2     7     2
26       5    10    15       6     8     3
27       5    10    15       5     9     4
28       5    10    15       8     0     5
29       5    10    15       8    11    10

In [12]:
pd.merge(d1,d2,how="right",right_on="key4",left_on="key2")  # when the columns are not same

   key1_x  key2  key3  key1_y  key4  key5
0     1.0   6.0  11.0       1     6     1
1     2.0   7.0  12.0       2     7     2
2     3.0   8.0  13.0       6     8     3
3     4.0   9.0  14.0       5     9     4
4     NaN   NaN   NaN       8     0     5
5     NaN   NaN   NaN       8    11    10

In [13]:
# join --> works on index merge works on columns

In [3]:
df["name_len"] = df["name"].apply(len)
df

,taxonomy_id,name,parent_id,parent_name,name_len
0,101,Emergency,NaN,NaN,9
1,101-01,Disaster Response,101,Emergency,17
2,101-02,Emergency Cash,101,Emergency,14
3,101-02-01,Help Pay for Food,101-02,Emergency Cash,17
4,101-02-02,Help Pay for Healthcare,101-02,Emergency Cash,23
...,...,...,...,...,...
285,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid,16
286,111-02,Mediation,111,Legal,9
287,111-03,Notary,111,Legal,6
288,111-04,Representation,111,Legal,14
289,111-05,Translation & Interpretation,111,Legal,28