In [1]:
import pandas as pd

data = {
'Name' : ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 
'Age' : [25, 30, 35, 40, 45], 
'Department' :  ['HR', 'IT', 'Finance', 'Marketing', 'Operations']
}

In [40]:
dataframe = pd.DataFrame(data)
dataframe

      Name  Age  Department
0    Alice   25          HR
1      Bob   30          IT
2  Charlie   35     Finance
3    David   40   Marketing
4      Eve   45  Operations

In [4]:
dataframe[dataframe.loc[:,'Age']>30]

      Name  Age  Department
2  Charlie   35     Finance
3    David   40   Marketing
4      Eve   45  Operations

In [5]:
dataframe.iloc[3,:]

Name              David
Age                  40
Department    Marketing
Name: 3, dtype: object

In [7]:
dataframe.iloc[:,:2]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4      Eve   45

In [9]:
dataframe.iloc[:3,:2]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:
dataframe.loc[3,"Age"]=42
dataframe

      Name  Age  Department
0    Alice   25          HR
1      Bob   30          IT
2  Charlie   35     Finance
3    David   42   Marketing
4      Eve   45  Operations

In [41]:
dataframe

      Name  Age  Department
0    Alice   25          HR
1      Bob   30          IT
2  Charlie   35     Finance
3    David   40   Marketing
4      Eve   45  Operations

In [46]:
it_index=dataframe[dataframe.loc[:,'Department']=='IT'].index

In [47]:
it_index

Index([1], dtype='int64')

In [49]:
dataframe.loc[it_index,'Department']='Tech Support'

In [50]:
dataframe

      Name  Age    Department
0    Alice   25            HR
1      Bob   30  Tech Support
2  Charlie   35       Finance
3    David   40     Marketing
4      Eve   45    Operations

In [52]:
dataframe

      Name  Age    Department
0    Alice   25            HR
1      Bob   30  Tech Support
2  Charlie   35       Finance
3    David   40     Marketing
4      Eve   45    Operations

In [61]:
dataframe.iloc[2,1]=32
dataframe

      Name  Age    Department
0    Alice   25            HR
1      Bob   30  Tech Support
2  Charlie   32       Finance
3    David   40     Marketing
4      Eve   45    Operations